// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PilotLife.Database.Data;

#nullable disable

namespace PilotLife.Database.Migrations
{
    [DbContext(typeof(PilotLifeDbContext))]
    [Migration("20251214181216_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PilotLife.Domain.Entities.Aircraft", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtcModel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("atc_model");

                    b.Property<string>("AtcType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("atc_type");

                    b.Property<string>("Category")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<double>("CruiseSpeedKts")
                        .HasColumnType("double precision")
                        .HasColumnName("cruise_speed_kts");

                    b.Property<double>("EmptyWeightLbs")
                        .HasColumnType("double precision")
                        .HasColumnName("empty_weight_lbs");

                    b.Property<int>("EngineType")
                        .HasColumnType("integer")
                        .HasColumnName("engine_type");

                    b.Property<string>("EngineTypeStr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("engine_type_str");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approved");

                    b.Property<double>("MaxGrossWeightLbs")
                        .HasColumnType("double precision")
                        .HasColumnName("max_gross_weight_lbs");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<int>("NumberOfEngines")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_engines");

                    b.Property<string>("SimulatorVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("simulator_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("aircraft", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.AircraftRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AircraftTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("aircraft_title");

                    b.Property<string>("AtcModel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("atc_model");

                    b.Property<string>("AtcType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("atc_type");

                    b.Property<string>("Category")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<double>("CruiseSpeedKts")
                        .HasColumnType("double precision")
                        .HasColumnName("cruise_speed_kts");

                    b.Property<double>("EmptyWeightLbs")
                        .HasColumnType("double precision")
                        .HasColumnName("empty_weight_lbs");

                    b.Property<int>("EngineType")
                        .HasColumnType("integer")
                        .HasColumnName("engine_type");

                    b.Property<string>("EngineTypeStr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("engine_type_str");

                    b.Property<double>("MaxGrossWeightLbs")
                        .HasColumnType("double precision")
                        .HasColumnName("max_gross_weight_lbs");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<int>("NumberOfEngines")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_engines");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_notes");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("SimulatorVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("simulator_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AircraftTitle");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("aircraft_requests", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country");

                    b.Property<int?>("ElevationFt")
                        .HasColumnType("integer")
                        .HasColumnName("elevation_ft");

                    b.Property<string>("IataCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("iata_code");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ident");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Municipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipality");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IataCode");

                    b.HasIndex("Ident")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("airports", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.FlightFinancials", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CrewCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("crew_cost");

                    b.Property<decimal>("DamagePenalty")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("damage_penalty");

                    b.Property<decimal>("FuelCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fuel_cost");

                    b.Property<decimal>("FuelEfficiencyBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fuel_efficiency_bonus");

                    b.Property<decimal>("HandlingFees")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("handling_fees");

                    b.Property<decimal>("IncidentPenalty")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("incident_penalty");

                    b.Property<decimal>("InsuranceCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("insurance_cost");

                    b.Property<decimal>("JobRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("job_revenue");

                    b.Property<decimal>("LandingBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("landing_bonus");

                    b.Property<decimal>("LandingFees")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("landing_fees");

                    b.Property<decimal>("LatePenalty")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("late_penalty");

                    b.Property<decimal>("MaintenanceCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("maintenance_cost");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<decimal>("NavigationFees")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("navigation_fees");

                    b.Property<decimal>("OnTimeBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("on_time_bonus");

                    b.Property<decimal>("OtherBonuses")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("other_bonuses");

                    b.Property<Guid>("TrackedFlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracked_flight_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackedFlightId")
                        .IsUnique();

                    b.ToTable("flight_financials", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.FlightJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualPayout")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("actual_payout");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_failed");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<int>("ReputationChange")
                        .HasColumnType("integer")
                        .HasColumnName("reputation_change");

                    b.Property<Guid>("TrackedFlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracked_flight_id");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer")
                        .HasColumnName("xp_earned");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("TrackedFlightId");

                    b.HasIndex("TrackedFlightId", "JobId")
                        .IsUnique();

                    b.ToTable("flight_jobs", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ArrivalAirportId")
                        .HasColumnType("integer")
                        .HasColumnName("arrival_airport_id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cargo_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("integer")
                        .HasColumnName("departure_airport_id");

                    b.Property<double>("DistanceNm")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_nm");

                    b.Property<int>("EstimatedFlightTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_flight_time_minutes");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<decimal>("Payout")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("payout");

                    b.Property<string>("RequiredAircraftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("required_aircraft_type");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("IsCompleted");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.PlayerWorld", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("CreditScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(650)
                        .HasColumnName("credit_score");

                    b.Property<int?>("CurrentAirportId")
                        .HasColumnType("integer")
                        .HasColumnName("current_airport_id");

                    b.Property<int>("FailedDeliveries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_deliveries");

                    b.Property<int?>("HomeAirportId")
                        .HasColumnType("integer")
                        .HasColumnName("home_airport_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_active_at");

                    b.Property<DateTimeOffset?>("LastViolationAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_violation_at");

                    b.Property<int>("LateDeliveries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("late_deliveries");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<int>("OnTimeDeliveries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("on_time_deliveries");

                    b.Property<decimal>("ReputationScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasDefaultValue(3.0m)
                        .HasColumnName("reputation_score");

                    b.Property<decimal>("TotalEarnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_earnings");

                    b.Property<int>("TotalFlightMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_flight_minutes");

                    b.Property<int>("TotalFlights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_flights");

                    b.Property<int>("TotalJobsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_jobs_completed");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_spent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("ViolationPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("violation_points");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAirportId");

                    b.HasIndex("HomeAirportId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorldId");

                    b.HasIndex("UserId", "WorldId")
                        .IsUnique();

                    b.ToTable("player_worlds", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_global");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_role");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Permission")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("permission");

                    b.Property<bool>("IsGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_granted");

                    b.HasKey("RoleId", "Permission");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.TrackedFlight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AircraftIcaoType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("aircraft_icao_type");

                    b.Property<Guid?>("AircraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("aircraft_id");

                    b.Property<string>("AircraftTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("aircraft_title");

                    b.Property<int?>("ArrivalAirportId")
                        .HasColumnType("integer")
                        .HasColumnName("arrival_airport_id");

                    b.Property<string>("ArrivalIcao")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("arrival_icao");

                    b.Property<DateTimeOffset?>("ArrivalTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("arrival_time");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConnectorSessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("connector_session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<double?>("CurrentAltitude")
                        .HasColumnType("double precision")
                        .HasColumnName("current_altitude");

                    b.Property<double?>("CurrentGroundSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("current_ground_speed");

                    b.Property<double?>("CurrentHeading")
                        .HasColumnType("double precision")
                        .HasColumnName("current_heading");

                    b.Property<double?>("CurrentLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("current_latitude");

                    b.Property<double?>("CurrentLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("current_longitude");

                    b.Property<int?>("DepartureAirportId")
                        .HasColumnType("integer")
                        .HasColumnName("departure_airport_id");

                    b.Property<string>("DepartureIcao")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("departure_icao");

                    b.Property<DateTimeOffset?>("DepartureTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("departure_time");

                    b.Property<double>("DistanceNm")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_nm");

                    b.Property<double?>("EndFuelGallons")
                        .HasColumnType("double precision")
                        .HasColumnName("end_fuel_gallons");

                    b.Property<int>("FlightTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("flight_time_minutes");

                    b.Property<double?>("FuelUsedGallons")
                        .HasColumnType("double precision")
                        .HasColumnName("fuel_used_gallons");

                    b.Property<int>("HardLandingCount")
                        .HasColumnType("integer")
                        .HasColumnName("hard_landing_count");

                    b.Property<double?>("LandingRate")
                        .HasColumnType("double precision")
                        .HasColumnName("landing_rate");

                    b.Property<DateTimeOffset?>("LastPositionUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_position_update");

                    b.Property<double>("MaxAltitude")
                        .HasColumnType("double precision")
                        .HasColumnName("max_altitude");

                    b.Property<double>("MaxGroundSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("max_ground_speed");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("OverspeedCount")
                        .HasColumnType("integer")
                        .HasColumnName("overspeed_count");

                    b.Property<double?>("PayloadWeightLbs")
                        .HasColumnType("double precision")
                        .HasColumnName("payload_weight_lbs");

                    b.Property<int>("StallWarningCount")
                        .HasColumnType("integer")
                        .HasColumnName("stall_warning_count");

                    b.Property<double?>("StartFuelGallons")
                        .HasColumnType("double precision")
                        .HasColumnName("start_fuel_gallons");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<double?>("TotalWeightLbs")
                        .HasColumnType("double precision")
                        .HasColumnName("total_weight_lbs");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("ConnectorSessionId");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("State");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId", "State");

                    b.ToTable("tracked_flights", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentAirportId")
                        .HasColumnType("integer")
                        .HasColumnName("current_airport_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("experience_level");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<int?>("HomeAirportId")
                        .HasColumnType("integer")
                        .HasColumnName("home_airport_id");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<bool>("NewsletterSubscribed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("newsletter_subscribed");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("TotalFlightMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_flight_minutes");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAirportId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HomeAirportId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorldId");

                    b.HasIndex("UserId", "RoleId", "WorldId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AircraftPriceMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("aircraft_price_multiplier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditRecoveryMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("credit_recovery_multiplier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("DetectionRiskMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("detection_risk_multiplier");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<decimal>("FineMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("fine_multiplier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<decimal>("JobExpiryMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("job_expiry_multiplier");

                    b.Property<decimal>("JobPayoutMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("job_payout_multiplier");

                    b.Property<decimal>("LicenseCostMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("license_cost_multiplier");

                    b.Property<decimal>("LoanInterestMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("loan_interest_multiplier");

                    b.Property<decimal>("MaintenanceCostMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("maintenance_cost_multiplier");

                    b.Property<int>("MaxPlayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_players");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<decimal>("StartingCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("starting_capital");

                    b.Property<decimal>("WorkerSalaryMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("worker_salary_multiplier");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.WorldSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AircraftPriceMultiplierOverride")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("aircraft_price_multiplier_override");

                    b.Property<bool>("AllowIllegalCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_illegal_cargo");

                    b.Property<bool>("AllowNewPlayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_new_players");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("EnableAICrews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enable_ai_crews");

                    b.Property<bool>("EnableAircraftRental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enable_aircraft_rental");

                    b.Property<bool>("EnableAuctions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enable_auctions");

                    b.Property<bool>("EnableChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enable_chat");

                    b.Property<bool>("EnableReporting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enable_reporting");

                    b.Property<decimal?>("JobPayoutMultiplierOverride")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("job_payout_multiplier_override");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<decimal?>("MaintenanceCostMultiplierOverride")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("maintenance_cost_multiplier_override");

                    b.Property<int>("MaxActiveJobsPerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_active_jobs_per_player");

                    b.Property<int>("MaxAircraftPerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_aircraft_per_player");

                    b.Property<int>("MaxLoansPerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_loans_per_player");

                    b.Property<int>("MaxWorkersPerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("max_workers_per_player");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<bool>("RequireApprovalToJoin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("require_approval_to_join");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("LastModifiedByUserId");

                    b.HasIndex("WorldId")
                        .IsUnique();

                    b.ToTable("world_settings", (string)null);
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.AircraftRequest", b =>
                {
                    b.HasOne("PilotLife.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PilotLife.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RequestedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.FlightFinancials", b =>
                {
                    b.HasOne("PilotLife.Domain.Entities.TrackedFlight", "TrackedFlight")
                        .WithOne("Financials")
                        .HasForeignKey("PilotLife.Domain.Entities.FlightFinancials", "TrackedFlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedFlight");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.FlightJob", b =>
                {
                    b.HasOne("PilotLife.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PilotLife.Domain.Entities.TrackedFlight", "TrackedFlight")
                        .WithMany("FlightJobs")
                        .HasForeignKey("TrackedFlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("TrackedFlight");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.Job", b =>
                {
                    b.HasOne("PilotLife.Domain.Entities.Airport", "ArrivalAirport")
                        .WithMany()
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PilotLife.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PilotLife.Domain.Entities.Airport", "DepartureAirport")
                        .WithMany()
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalAirport");

                    b.Navigation("AssignedToUser");

                    b.Navigation("DepartureAirport");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.PlayerWorld", b =>
                {
                    b.HasOne("PilotLife.Domain.Entities.Airport", "CurrentAirport")
                        .WithMany()
                        .HasForeignKey("CurrentAirportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PilotLife.Domain.Entities.Airport", "HomeAirport")
                        .WithMany()
                        .HasForeignKey("HomeAirportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PilotLife.Domain.Entities.User", "User")
                        .WithMany("PlayerWorlds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PilotLife.Domain.Entities.World", "World")
                        .WithMany("Players")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentAirport");

                    b.Navigation("HomeAirport");

                    b.Navigation("User");

                    b.Navigation("World");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PilotLife.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("PilotLife.Domain.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.TrackedFlight", b =>
                {
                    b.HasOne("PilotLife.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PilotLife.Domain.Entities.Airport", "ArrivalAirport")
                        .WithMany()
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PilotLife.Domain.Entities.Airport", "DepartureAirport")
                        .WithMany()
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PilotLife.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PilotLife.Domain.Entities.User", null)
                        .WithMany("TrackedFlights")
                        .HasForeignKey("UserId1");

                    b.Navigation("Aircraft");

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.User", b =>
                {
                    b.HasOne("PilotLife.Domain.Entities.Airport", "CurrentAirport")
                        .WithMany()
                        .HasForeignKey("CurrentAirportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PilotLife.Domain.Entities.Airport", "HomeAirport")
                        .WithMany()
                        .HasForeignKey("HomeAirportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentAirport");

                    b.Navigation("HomeAirport");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("PilotLife.Domain.Entities.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PilotLife.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PilotLife.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PilotLife.Domain.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GrantedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");

                    b.Navigation("World");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.WorldSettings", b =>
                {
                    b.HasOne("PilotLife.Domain.Entities.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PilotLife.Domain.Entities.World", "World")
                        .WithOne("Settings")
                        .HasForeignKey("PilotLife.Domain.Entities.WorldSettings", "WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastModifiedByUser");

                    b.Navigation("World");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.TrackedFlight", b =>
                {
                    b.Navigation("Financials");

                    b.Navigation("FlightJobs");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.User", b =>
                {
                    b.Navigation("PlayerWorlds");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TrackedFlights");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PilotLife.Domain.Entities.World", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
